org.gradle.jvmargs=-Xmx1G

# Plugins
lombok_version=8.6

# Fabric Properties
# https://fabricmc.net/versions.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.4
loom_version=1.14-SNAPSHOT


# Mod Properties
mod_version=1.7.4
maven_group=me.lortseam
archives_base_name=noweathereffects

# Dependencies
completeconfig_version=2.5.1
modmenu_version=8.0.0-beta.2
